osx_image: xcode7.2
language: objective-c

before_install:
- brew update
- brew install carthage
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
- carthage update --no-build --platform iOS
- carthage bootstrap --platform iOS

script:
- xctool clean build -project Spots.xcodeproj -scheme Spots-iOS -sdk iphonesimulator
- xctool test -project Spots.xcodeproj -scheme Spots-iOS -sdk iphonesimulator
